### ISSUE TITLE
Wallpaper please!

### ISSUE THREAD

**Issue by ItsTerm1n4l** [closebox73/Star_Graves#1]
could I have the wallpaper shown here please?
![preview](https://github.com/closebox73/Star_Graves/assets/118511626/70216c2d-2b61-4563-bfb8-0d876af619df)
I found this screenshot here. https://www.pling.com/p/1839849
Great work on the conky themes BTW.

**Comment by closebox73** [comment]
@ItsTerm1n4l check here https://wallhere.com/en/wallpaper/510596

**Comment by ItsTerm1n4l** [comment]
Thank you!
